# Generated by Django 3.2.25 on 2025-05-28 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_architect_id_header_tariff_architect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('have_visa', models.BooleanField(default=False)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='core.header_tariff')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='core.project')),
            ],
        ),
    ]
