# Generated by Django 3.2.25 on 2025-05-28 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header_tariff',
            name='architect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='core.architect'),
        ),
    ]
