# Generated by Django 3.2.25 on 2025-05-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_project_percentaje_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='percentaje_visa',
            field=models.FloatField(default=0.0),
        ),
    ]
