# Generated by Django 3.2.25 on 2025-05-26 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250526_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tariff_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tariff_date', models.DateField()),
                ('architect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='core.architect')),
            ],
        ),
    ]
