# Generated by Django 3.2.25 on 2025-05-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_header_tariff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header_tariff',
            old_name='architect_id',
            new_name='architect',
        ),
    ]
