# Generated by Django 3.2.25 on 2025-06-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_header_tariff_architect'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='tariff_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
