# Generated by Django 3.2.25 on 2025-06-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tariff_tariff_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='ci',
            field=models.CharField(error_messages={'unique': 'El número de CI ya existe.'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='architect',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'El número de teléfono ya existe.'}, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='architect',
            name='register_number',
            field=models.CharField(error_messages={'unique': 'El número de registro ya existe.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(error_messages={'unique': 'El proyecto ya existe.'}, max_length=255, unique=True),
        ),
    ]
